// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /categories"
  | "GET /me/expenses"
  | "GET /me/expenses/{expenseId}"
  | "GET /me/team/expenses"
  | "POST /me/expenses"
  | "POST /me/team/expenses/{expenseId}/approve"
  | "POST /me/team/expenses/{expenseId}/reject";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /categories": { kind: "public" },
  "GET /me/expenses": { kind: "scope", scope: "expenses:read" },
  "GET /me/expenses/{expenseId}": { kind: "scope", scope: "expenses:read" },
  "GET /me/team/expenses": { kind: "scope", scope: "expenses:review-team" },
  "POST /me/expenses": { kind: "scope", scope: "expenses:submit" },
  "POST /me/team/expenses/{expenseId}/approve": { kind: "scope", scope: "expenses:approve" },
  "POST /me/team/expenses/{expenseId}/reject": { kind: "scope", scope: "expenses:reject" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
